# Generated by Django 4.0.2 on 2022-06-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Credit', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('PRN', models.IntegerField(primary_key=True, serialize=False)),
                ('Roll', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=20)),
                ('Division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('Batch', models.CharField(max_length=2)),
                ('Branch', models.CharField(choices=[('AI & DS', 'Ai'), ('Mechanical', 'Mech'), ('Civil', 'Civil'), ('IT', 'It'), ('CS', 'Cs'), ('ENTC', 'Entc')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.DateField()),
                ('TimeSlot', models.TimeField()),
                ('present', models.BooleanField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.course')),
            ],
        ),
    ]
